### ISSUE TITLE
here is no license file in this repo.

### ISSUE THREAD

**Issue by shenliqing** [gpustack/gpustack-ui#236]
Need to add a license file in codebase such as "[Apache-2.0 license](https://github.com/gpustack/gpustack?tab=Apache-2.0-1-ov-file#)"  as [gpustack](https://github.com/gpustack/gpustack) main project: [LICENSE](https://github.com/gpustack/gpustack/blob/main/LICENSE), or "[MIT license](https://github.com/gpustack/gguf-packer-go?tab=MIT-1-ov-file#)"  as [gguf-packer-go](https://github.com/gpustack/gguf-packer-go) sub-project: [LICENSE](https://github.com/gpustack/gguf-packer-go/blob/main/LICENSE)

**Comment by gitlawr** [comment]
Available in main
